### ISSUE TITLE
Change "Guest access" to "Offline with bots"

### ISSUE THREAD

**Issue by Cwpute** [mytja/Tarok#59]
I was trying to start a game against bots but couldn't find where ut was. Out of curiosity, i clicked on "Guest access" and was surprised it worked, even though i was offline. But this is where i had to go for offline matches against bots!

"Guest access" suggests it is a one-time only handle you'll be getting for online use. Which it isn't! (yet, perhaps)
Rename this button to "Offline with bots" so it is better understandable what it does.

**Comment by mytja** [comment]
Hi, I agree, it can be confusing. That's without a doubt a change for the next update. I still need to migrate over to newer version of Flutter (that's why my web builds are failing), but when I finish it, I'll change it.

**Comment by mytja** [comment]
Fixed by https://github.com/mytja/Tarok/commit/72553dbc2f81cc7e5144123a7e4d53ae27cb939a#diff-fd9d5db38d434f83beab319352d1fb79a614af7ed68a600bd4c06d779918cb3a
