### ISSUE TITLE
Potential points for winning a round

### ISSUE THREAD

**Issue by Cwpute** [mytja/Tarok#68]
When licitating, i'd like to be able to quickly see the potential points i can make from each type of game. It would help me weight in risk and reward at a glance.

This could be achieved by showing a hovering window above game buttons when long pressing them.
For example, if i were to longpress the button `Color Valat` while licitating, a small window above my thumb would appear with the points i'd get if i were to win it: `125`.

**Comment by mytja** [comment]
Done. Released in 1.0.2, awaiting Google Play approval and F-Droid update. Updated app is already available on the website https://palcka.si.
