### ISSUE TITLE
In-game Options button inconsistency

### ISSUE THREAD

**Issue by Cwpute** [mytja/Tarok#70]
The little cog icon should allow you to access the Options menu, which features both the Options page and the Guide page buttons.
But almost every time i try to tap on that button while in a game, the options page instantly opens.

Might be because the app wrongly registers a double-tap ? my guess is that this is a legacy of when this buton would not bring any menu but instead directly send you to the options page.

**Comment by mytja** [comment]
That menu is too bloated. Especially on mobile devices. I'll remove some options when I have some time.

**Comment by mytja** [comment]
This is correctly assumed as legacy. Fixed in commit https://github.com/mytja/Tarok/commit/082d7534278b9e07d0bcf335667e824af4752f7a.
