### ISSUE TITLE
Clearly signifies it is your turn

### ISSUE THREAD

**Issue by Cwpute** [mytja/Tarok#71]
I keep getting myself in situations in which right after licitation ends and the game begins, i wait for someone to play… only to realize i've got to play first.

I'd appreciate if there was a clear way for the game to tell me who should start the round.

Maybe a simple fading message that would say "It is your turn" or something like that ? or a symbol next to the player's coloured box, like the symbol used for the colour of the king called. Something like 🖐️ or 💭 for example.

**Comment by mytja** [comment]
![Image](https://github.com/mytja/Tarok/assets/52399966/a4a4e2ca-f072-4639-a235-7df60963246e)
