### ISSUE TITLE
Red symbols blend with coloured background

### ISSUE THREAD

**Issue by Cwpute** [mytja/Tarok#72]
Black symbols are perfectly readable on my device: 
![Screenshot_20240223-011133 (1)](https://github.com/mytja/Tarok/assets/80604512/b1919ebb-505f-4a1e-8b13-9b8eccd6001d)
But red symbols can get hardqto distinguish: 
![Screenshot_20240223-010529 (1)](https://github.com/mytja/Tarok/assets/80604512/07989d66-6586-4f63-a71f-d7045007f55f)
![Screenshot_20240223-005247 (1)](https://github.com/mytja/Tarok/assets/80604512/df3125ee-ff50-440d-96ab-1fe790ca7a38)

This may only be because of the specific emoji font my device is using, but i have to squint a bit and weirdly angle my device to cliarly see which king was called again. Being a bit colourblind doesn't help me either…

I'd suggest having both black and red symbols be shown on a black background as to avoid this kind of situation, maybe with a red outline for red symbols, and black outline for black symbols if that helps you distinguish them better.

**Comment by mytja** [comment]
All symbols are white on respective (red or black) background.

Thanks for all your issues and suggestions. Your French translation has been implemented and will be released shortly in 1.0.5.

In case anything doesn't work as intended, do not hesitate to reopen the issue.

**Comment by Cwpute** [comment]
Good job on this issue.
However the symbols next tu the player name on the table are still blending with their background !

**Comment by mytja** [comment]
I'll have a look in the upcoming days

**Comment by mytja** [comment]
Which symbols exactly blend with the background? 😅

![Uploading Screenshot_20240908-002129_Palčka.png …]()

**Comment by Cwpute** [comment]
this one: [![Screenshot-20240908-010400-1.png](https://i.postimg.cc/jj3npxT5/Screenshot-20240908-010400-1.png)](https://postimg.cc/cKYJYNry)

**Comment by mytja** [comment]
Thanks.
