### ISSUE TITLE
Highlight leading/winning player

### ISSUE THREAD

**Issue by Cwpute** [mytja/Tarok#77]
I'd like it if it was easier to tell who is leading the current round, or who just won the deck. 
You could set a contour around the square of the player (on the table) who is leading the round, or around that of the player who just won the deck, until the next round begins.
Another way to do it would be to animate the cards for the current deck moving towards the player who just won it, so that it replicates what happens IRL.
Would be helpful to better evaluate rounds, who won what and how many times.

**Comment by mytja** [comment]
This one I don't understand completely. Isn't it evident enough who started the deck of 3/4 when you look at dropped cards (the first dropped card is the lowest)?

**Comment by Cwpute** [comment]
sorry, i got mixed up: i meant rounds, not hands.
i don't mean to highlight the player who lays down their card first, i mean to highlight the player who played the most powerful card this round, and thus is leading the current round.

**Comment by Cwpute** [comment]
i edited my issue with hopefully better wording

**Comment by mytja** [comment]
![image](https://github.com/user-attachments/assets/449c6a6e-1d64-4144-9f42-5693e9661c54)

I think I understood you correctly.

**Comment by mytja** [comment]
There's now a new accessibility setting, "Show most powerful card". It's off by default, as it can be distracting to gameplay.

Thank you for your rapid responses. I will release a new version and get updates to Google Play & F-Droid later today.

**Comment by mytja** [comment]
The only two added translations were:

- Show most powerful card
- Marks the currently most powerful card in the round with red.

If you want, you can just respond with French translations for me to include in a new release, however it's not necessary.

**Comment by Cwpute** [comment]
Thanks ! yes, here is the french translation:
* Montrer la carte la plus puissante
* Marque en rouge la carte qui est actuellement la plus puissante du pli
